<?php

namespace AppBundle\Repository;

/**
 * DemandeAcompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
