<?php

namespace AppBundle\Repository;

/**
 * DemandeRibSalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRibSalarieRepository extends \Doctrine\ORM\EntityRepository
{
}
