<?php

namespace AppBundle\Repository;

/**
 * DemandeComplexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeComplexeRepository extends \Doctrine\ORM\EntityRepository
{
}
