<?php

namespace AppBundle\Repository;

/**
 * DemandeSimpleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeSimpleRepository extends \Doctrine\ORM\EntityRepository
{
}
