<?php

namespace AppBundle\Repository;

/**
 * DemandeAvenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAvenantRepository extends \Doctrine\ORM\EntityRepository
{
}
