<?php

namespace AppBundle\Repository;

/**
 * DemandeEmbaucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEmbaucheRepository extends \Doctrine\ORM\EntityRepository
{
  //Fonction infosDemandeSelf: Retourne un array avec toutes les infos du collab d'une demande d'embauche
  //Paramètre : id Demande
  //Return array
  public function infosDemandeSelf($idDemandeEmbauche){
    $collaborateur=[];
    $requete = $this->findOneBy(array('id' => $idDemandeEmbauche));

    $collaborateur['matricule']      = '0000';
    $collaborateur['nom']            = $requete->getNom();
    $collaborateur['prenom']         = $requete->getPrenom();
    $collaborateur['dateNaissance']  = $requete->getDateNaissance()->format('d-m-Y');
    $collaborateur['villeNaissance'] = $requete->getVilleNaissance();
    $collaborateur['paysNaissance']  = $requete->getPaysNaissance();
    $collaborateur['sexe']           = $requete->getSexe();
    $collaborateur['nationalite']    = $requete->getNationalite();
    $collaborateur['niveau']         = $requete->getNiveau();
    $collaborateur['echelon']        = $requete->getEchelon();
    $collaborateur['adresse1']       = $requete->getAdresse1();
    $collaborateur['adresse2']       = $requete->getAdresse2();
    $collaborateur['codePostal']     = $requete->getCodepostal();
    $collaborateur['ville' ]         = $requete->getVille();
    $collaborateur['telephone1']     = $requete->getTelephone();
    $collaborateur['telephone2']     = '';
    $collaborateur['email']          = $requete->getEmail();

    return $collaborateur;
   }
}
