<?php

namespace AppBundle\Repository;

/**
 * DemandeSoldeToutCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeSoldeToutCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
