<?php

namespace AppBundle\Repository;

/**
 * DemandePromesseEmbaucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePromesseEmbaucheRepository extends \Doctrine\ORM\EntityRepository
{
}
