<?php

namespace AppBundle\Repository;

/**
 * DemandeAttestationSalaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAttestationSalaireRepository extends \Doctrine\ORM\EntityRepository
{
}
