<?php

namespace AppBundle\Repository;

/**
 * DemandeEmbaucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEmbaucheRepository extends \Doctrine\ORM\EntityRepository
{
}
