<?php

namespace AppBundle\Repository;

/**
 * DemandeCongeParentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCongeParentalRepository extends \Doctrine\ORM\EntityRepository
{
}
