<?php

namespace AppBundle\Repository;

/**
 * DemandeRuptureCdd
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRuptureCdd extends \Doctrine\ORM\EntityRepository
{
}
