<?php

namespace AppBundle\Repository;

/**
 * DemandeRibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRibRepository extends \Doctrine\ORM\EntityRepository
{
}
