<?php

namespace AppBundle\Repository;

/**
 * DemandeAbsencesInjustifieesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAbsencesInjustifieesRepository extends \Doctrine\ORM\EntityRepository
{
}
