<?php

namespace AppBundle\Repository;

/**
 * DemandeDemissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDemissionRepository extends \Doctrine\ORM\EntityRepository
{
}
