<?php

namespace AppBundle\Repository;

/**
 * Retards
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Retards extends \Doctrine\ORM\EntityRepository
{
}
