<?php

namespace AppBundle\Repository;

/**
 * RibSalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RibSalarieRepository extends \Doctrine\ORM\EntityRepository
{
}
