<?php

namespace AppBundle\Repository\Admin;

/**
 * Notification
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Notification extends \Doctrine\ORM\EntityRepository
{
}
