<?php

namespace ApiBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ApiBundle\Entity\Personnel;

/**
 * PersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnelRepository extends EntityRepository
{
    public function getNb($idPerso,$idSalon) {
          $nb = $this->createQueryBuilder('d')
              ->select('COUNT(d)')
              ->join('d.salon', 'm')
              ->where('d.matricule = :idPerso')
              ->andwhere('m.sage = :idSalon')
              ->setParameter('idPerso',$idPerso)
              ->setParameter('idSalon',$idSalon)
              ->getQuery()
              ->getResult();

            return $nb[0][1];
      }

    public function getPerso($listeAccount,$idSalon){
        $personnel = new Personnel();

        foreach ($listeAccount as $key => $value) {
                if ( self::getNb($value,$idSalon) > 0 ){
                     $p = $this->findOneBy(array('matricule' => $value));
                     $listPerso[$p->getNom().' '.$p->getPrenom()] = $value;
                }
         }
        return $listPerso;
    }


}
