<?php

namespace ApiBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ApiBundle\Entity\Salon;

/**
 * SalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonRepository extends EntityRepository
{
    // Fonction infosSalon : Retourne les infos d'un salon
    // Paramètre : idsalon
    // Return array
    public function infosSalon($idSalon) {
          $salon=[];
          $requete = $this->findOneBy(array('sage' => $idSalon));

              $salon['appelation'] = $requete->getAppelation();
              $salon['enseigne'] =  $requete->getEnseigne()->getNom();
              $salon['formeJuridique'] =  $requete->getFormeJuridique();
              $salon['rcsVille'] =  $requete->getRcsVille();
              $salon['codeNaf'] =  $requete->getCodeNaf();
              $salon['siren'] =  $requete->getSiren();
              $salon['capital'] =  $requete->getCapital();
              $salon['raisonSociale'] =  $requete->getRaisonSociale();
              $salon['adresse1'] =  $requete->getAdresse1();
              $salon['adresse2'] =  $requete->getAdresse2();
              $salon['codePostal'] =  $requete->getCodePostal();
              $salon['ville'] =  $requete->getVille();
              $salon['telephone1'] =  $requete->getTelephone1();
              $salon['telephone2'] =  $requete->getTelephone2();
              $salon['email'] =  $requete->getEmail();
              $salon['codeMarlix'] =  $requete->getCodeMarlix();
              $salon['dateOuverture'] =  $requete->getDateOuverture();

              return $salon;
      }


}
