<?php

namespace ApiBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ApiBundle\Entity\Salon;

/**
 * SalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonRepository extends EntityRepository
{
    public function infosSalon($idSalon) {
          $salon=[];
          $requete = $this->findOneBy(array('sage' => $idSalon));

              $salon['appelation'] = $requete->getAppelation();
              $salon['enseigne'] =  $requete->getEnseigne()->getNom();
              $salon['formeJuridique'] =  $salon->getFormeJuridique();
              $salon['rcsVille'] =  $salon->getRcsVille();
              $salon['codeNaf'] =  $salon->getCodeNaf();
              $salon['siren'] =  $salon->getSiren();
              $salon['capital'] =  $salon->getCapital();
              $salon['raisonSociale'] =  $salon->getRaisonSociale();
              $salon['adresse1'] =  $salon->getAdresse1();
              $salon['adresse2'] =  $salon->getAdresse2();
              $salon['codePostal'] =  $salon->getCodePostal();
              $salon['ville'] =  $salon->getVille();
              $salon['telephone1'] =  $salon->getTelephone1();
              $salon['telephone2'] =  $salon->getTelephone2();
              $salon['email'] =  $salon->getEmail();
              $salon['codeMarlix'] =  $salon->getCodeMarlix();
              $salon['dateOuverture'] =  $salon->getDateOuverture();

              return $salon;
      }


}
